export const data = [
  {
    issueId: 'Dusty',
    issueTitle: 'Kuvalis',
    createdBy: 'Randy63@yahoo.com',
    assignedTo: 'Chief Creative Technician',
    dateCreated: '3/20/2014',
    dueDate: '3/20/2014',
    issueDescription: 'Cross-platform disintermediate workforce',
  },
  {
    issueId: "D'angelo",
    issueTitle: 'Moen',
    createdBy: 'Andrew88@hotmail.com',
    assignedTo: 'Forward Response Engineer',
    dateCreated: '3/9/2018',
    dueDate: '3/20/2014',
    issueDescription: 'Virtual local support',
  },
  {
    issueId: 'Devan',
    issueTitle: 'Reinger',
    createdBy: 'Melissa_Lockman@hotmail.com',
    assignedTo: 'Customer Intranet Consultant',
    dateCreated: '8/12/2020',
    dueDate: '3/20/2014',
    issueDescription: 'Pre-emptive composite hierarchy',
  },
  {
    issueId: 'Leonardo',
    issueTitle: 'Langworth',
    createdBy: 'Chadrick.Goldner87@gmail.com',
    assignedTo: 'Senior Security Manager',
    dateCreated: '7/25/2017',
    dueDate: '3/20/2014',
    issueDescription: 'Progressive real-time core',
  },
  {
    issueId: 'Douglas',
    issueTitle: 'Denesik',
    createdBy: 'Dante.Deckow@hotmail.com',
    assignedTo: 'Legacy Security Assistant',
    dateCreated: '4/12/2020',
    dueDate: '3/20/2014',
    issueDescription: 'Operative well-modulated info-mediaries',
  },
  {
    issueId: 'Jameson',
    issueTitle: 'Mayer',
    createdBy: 'Rosamond_Schuster@yahoo.com',
    assignedTo: 'Regional Division Planner',
    dateCreated: '10/30/2017',
    dueDate: '3/20/2014',
    issueDescription: 'Front-line intermediate firmware',
  },
  {
    issueId: 'Madaline',
    issueTitle: 'Quitzon',
    createdBy: 'Alex_Grimes82@hotmail.com',
    assignedTo: 'Corporate Paradigm Strategist',
    dateCreated: '1/17/2018',
    dueDate: '3/20/2014',
    issueDescription: 'Right-sized high-level algorithm',
  },
  {
    issueId: 'Wilfrid',
    issueTitle: 'Vandervort',
    createdBy: 'Buddy.Torphy@gmail.com',
    assignedTo: 'Legacy Functionality Specialist',
    dateCreated: '8/4/2014',
    dueDate: '3/20/2014',
    issueDescription: 'Focused interactive secured line',
  },
  {
    issueId: 'Chelsie',
    issueTitle: 'Mraz',
    createdBy: 'Ladarius_Thiel70@yahoo.com',
    assignedTo: 'Forward Infrastructure Representative',
    dateCreated: '1/6/2021',
    dueDate: '3/20/2014',
    issueDescription: 'Diverse attitude-oriented migration',
  },
  {
    issueId: 'Hassie',
    issueTitle: 'Bruen',
    createdBy: 'Clair76@gmail.com',
    assignedTo: 'Human Paradigm Designer',
    dateCreated: '4/28/2016',
    dueDate: '3/20/2014',
    issueDescription: 'Upgradable composite methodology',
  },
];