apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: react
  template:
    metadata:
      labels:
        component: react
    spec:
      containers:
        - name: react
          image: abijith007/trackademic-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: API_GATEWAY_SERVICE
              value: api-gateway-service.default.svc.cluster.local:4000          