apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: react
  template:
    metadata:
      labels:
        component: react
    spec:
      containers:
        - name: react
          image: frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: API_GATEWAY_SERVICE
              value: api-gateway-service.default.svc.cluster.local:4000
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "0.5"
              memory: "256Mi"      