apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: chatbot
  template:
    metadata:
      labels:
        component: chatbot
    spec:
      containers:
        - name: chatbot
          image: chatbot:latest
          ports:
            - containerPort: 4003
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"      