apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: notification-service
  template:
    metadata:
      labels:
        component: notification-service
    spec:
      containers:
        - name: notification-service
          image: abijith007/trackademic-notification-service:latest  
          imagePullPolicy: Always        
          ports:
            - containerPort: 4004
          env:
            - name: GMAIL_USER
              value: "parekhshakshi820@gmail.com"
            - name: GMAIL_PASSWORD
              value: "twtzvbxxqvgnpwwe"