apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    component: notification-service
  ports:
    - protocol: TCP
      port: 4004
      targetPort: 4004
  type: ClusterIP