apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  selector:
    component: api-gateway
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: LoadBalancer