apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-k8s-service-account
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:  
  replicas: 1
  selector:
    matchLabels:
      component: user-service
  template:
    metadata:
      labels:
        component: user-service
    spec:
      serviceAccountName: my-k8s-service-account
      containers:
        - name: user-service
          image: abijith007/trackademic-user-service:latest
          ports:
            - containerPort: 4001
          env:
            - name: NOTIFICATION_SERVICE
              value: notification-service.default.svc.cluster.local:4004
            - name: MYSQL_LINK
              value: mysql://root:trackademic@123@10.55.16.3:3306/trackademic
            - name: SECRET_KEY
              value: "secret_key"